# Name:         Jillian Quinn
# Course:       CPE 101       
# Instructor:   Kauffman
# Assignment:   Word Search Tests
# Term:         Winter 2019


import wordsearch

assert wordsearch.parse_word("Computer Science", 1) == "Science"
assert wordsearch.parse_word("Math Class", 0) == "Math"
assert wordsearch.parse_word("I am from Washington", 2) == "from"

assert wordsearch.find_word("WAQHGTTWEECBMIVQQELSAZXWKWIIILLDWLFXPIPVPONDTMVAMNOEDSOYQGOBLGQCKGMMCTYCSLOACUZMXVDMGSXCYZUUIUNIXFNU", "CALPOLY") == "CALPOLY: (DOWN) row: 1 column: 0"
assert wordsearch.find_word("WAQHGTTWEECBMIVQQELSAZXWKWIIILLDWLFXPIPVPONDTMVAMNOEDSOYQGOBLGQCKGMMCTYCSLOACUZMXVDMGSXCYZUUIUNIXFNU", "TEST") == "TEST: word not found"
assert wordsearch.find_word("WAQHGTTWEECBMIVQQELSAZXWKWIIILLDWLFXPIPVPONDTMVAMNOEDSOYQGOBLGQCKGMMCTYCSLOACUZMXVDMGSXCYZUUIUNIXFNU", "VIM") == "VIM: (BACKWARD) row: 1 column: 4"
assert wordsearch.find_word("WAQHGTTWEECBMIVQQELSAZXWKWIIILLDWLFXPIPVPONDTMVAMNOEDSOYQGOBLGQCKGMMCTYCSLOACUZMXVDMGSXCYZUUIUNIXFNU", "COMPILE") == "COMPILE: (UP) row: 6 column: 8"
assert wordsearch.find_word("WAQHGTTWEECBMIVQQELSAZXWKWIIILLDWLFXPIPVPONDTMVAMNOEDSOYQGOBLGQCKGMMCTYCSLOACUZMXVDMGSXCYZUUIUNIXFNU", "SLO") == "SLO: (FORWARD) row: 7 column: 2"


assert wordsearch.reverse_string("Hello") == "olleH"
assert wordsearch.reverse_string("jillian") == "naillij"
assert wordsearch.reverse_string("cup") == "puc"

assert wordsearch.transpose_string("abcdefghi", 3) == "adgbehcfi"
assert wordsearch.transpose_string("qwertyuiopasdfghjklz", 5) == "qyahwusjeidkrofltpgz"
assert wordsearch.transpose_string("asdf", 2) == "adsf"

assert wordsearch.find_row("LAORSCIIHCLOIBMODGHMAODAORBONIRLNMSCSSGRSLACKHLMMRHALEAOSOSSAMHTGRANDMHIGUERADCLLLIHTOOFMHCLHSRAMLAP", "HIGUERA", "(DOWN)") == 0
assert wordsearch.find_row("WCALPOLYXUABZDOEGCVUQMXWNDQSDIHIWLDSCLMUGVKFTOKOGNTQWXMYGASITQIPVQMCXXWEIIAGMUCFELIPMOCZYNESLV", "CALPOLY", "(DOWN)") == 1
assert wordsearch.find_row("WAQHGTTWEECBMIVQQELSAZXWKWIIILLDWLFXPIPVPONDTMVAMNOEDSOYQGOBLGQCKGMMCTYCSLOACUZMXVDMGSXCYZUUIUNIXFNU", "MIV", "(BACKWARD)") == 1
assert wordsearch.find_row("WCALPOLYXUABZDOEGCVUQMXWNDQSDIHIWLDSCLMUGVKFTOKOGNTQWXMYGASITQIPVQMCXXWEIIAGMUCFELIPMOCZYNESLV", "ELIPMOC", "(UP)") == 6
assert wordsearch.find_row("WAQHGTTWEECBMIVQQELSAZXWKWIIILLDWLFXPIPVPONDTMVAMNOEDSOYQGOBLGQCKGMMCTYCSLOACUZMXVDMGSXCYZUUIUNIXFNU", "SLO", "(FORWARD)") == 7
assert wordsearch.find_row("WCALPOLYXUABZDOEGCVUQMXWNDQSDIHIWLDSCLMUGVKFTOKOGNTQWXMYGASITQIPVQMCXXWEIIAGMUCFELIPMOCZYNESLV", "CALPOLY", "(DOWN)") == 1

assert wordsearch.find_column("LAORSCIIHCLOIBMODGHMAODAORBONIRLNMSCSSGRSLACKHLMMRHALEAOSOSSAMHTGRANDMHIGUERADCLLLIHTOOFMHCLHSRAMLAP", "HIGUERA", "(DOWN)") == 7
assert wordsearch.find_column("WCALPOLYXUABZDOEGCVUQMXWNDQSDIHIWLDSCLMUGVKFTOKOGNTQWXMYGASITQIPVQMCXXWEIIAGMUCFELIPMOCZYNESLV", "CALPOLY", "(DOWN)") == 0
assert wordsearch.find_column("WAQHGTTWEECBMIVQQELSAZXWKWIIILLDWLFXPIPVPONDTMVAMNOEDSOYQGOBLGQCKGMMCTYCSLOACUZMXVDMGSXCYZUUIUNIXFNU", "MIV", "(BACKWARD)") == 4
assert wordsearch.find_column("WCALPOLYXUABZDOEGCVUQMXWNDQSDIHIWLDSCLMUGVKFTOKOGNTQWXMYGASITQIPVQMCXXWEIIAGMUCFELIPMOCZYNESLV", "ELIPMOC", "(UP)") == 8
assert wordsearch.find_column("WAQHGTTWEECBMIVQQELSAZXWKWIIILLDWLFXPIPVPONDTMVAMNOEDSOYQGOBLGQCKGMMCTYCSLOACUZMXVDMGSXCYZUUIUNIXFNU", "SLO", "(FORWARD)") == 2
assert wordsearch.find_column("WCALPOLYXUABZDOEGCVUQMXWNDQSDIHIWLDSCLMUGVKFTOKOGNTQWXMYGASITQIPVQMCXXWEIIAGMUCFELIPMOCZYNESLV", "CALPOLY", "(DOWN)") == 0
